import { NextRequest, NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: NextRequest) {
  try {
    const { email } = await request.json();
    console.log(email);
    console.log('GMAIL_APP_PASSWORD exists:', !!process.env.GMAIL_APP_PASSWORD);
    console.log('GMAIL_USER exists:', !!process.env.GMAIL_USER);

    if (!email) {
      return NextResponse.json(
        { error: 'Email is required' },
        { status: 400 }
      );
    }

    // Check if Gmail credentials are configured
    if (!process.env.GMAIL_APP_PASSWORD) {
      console.error('GMAIL_APP_PASSWORD environment variable is not set');
      return NextResponse.json(
        { error: 'Email service is not configured. Please contact support.' },
        { status: 500 }
      );
    }

    // Create transporter for Gmail
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: process.env.GMAIL_USER || 'eyeric.info@gmail.com',
        pass: process.env.GMAIL_APP_PASSWORD,
      },
    });

    // Email content for admin
    const adminMailOptions = {
      from: process.env.GMAIL_USER || 'eyeric.info@gmail.com',
      to: 'eyeric.info@gmail.com',
      subject: 'New Newsletter Subscription - EYERIC',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1f2937; border-bottom: 2px solid #3b82f6; padding-bottom: 10px;">
            🎉 New Newsletter Subscription
          </h2>
          
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <h3 style="color: #374151; margin-top: 0;">Subscription Details:</h3>
            <p><strong>User Email:</strong> ${email}</p>
            <p><strong>Subscription Date:</strong> ${new Date().toLocaleString()}</p>
            <p><strong>Message:</strong> This user wants to connect with you and stay updated with EYERIC news!</p>
          </div>
          
          <div style="background-color: #dbeafe; padding: 15px; border-radius: 8px; border-left: 4px solid #3b82f6;">
            <p style="margin: 0; color: #1e40af;">
              <strong>Action Required:</strong> Consider reaching out to this subscriber or adding them to your email marketing list.
            </p>
          </div>
          
          <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #e5e7eb;">
            <p style="color: #6b7280; font-size: 14px;">
              This email was automatically generated by the EYERIC website newsletter subscription system.
            </p>
          </div>
        </div>
      `,
    };

    // Send email to admin
    await transporter.sendMail(adminMailOptions);

    // Optional: Send confirmation email to user
    const userMailOptions = {
      from: process.env.GMAIL_USER || 'eyeric.info@gmail.com',
      to: email,
      subject: 'Welcome to EYERIC Newsletter! 👓',
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h2 style="color: #1f2937; text-align: center;">
            🎉 Welcome to EYERIC!
          </h2>
          
          <div style="background-color: #f8fafc; padding: 20px; border-radius: 8px; margin: 20px 0;">
            <p style="color: #374151; font-size: 16px;">
              Thank you for subscribing to our newsletter! You're now part of our community of eyewear enthusiasts.
            </p>
            
            <p style="color: #374151; font-size: 16px;">
              We'll keep you updated with:
            </p>
            <ul style="color: #374151;">
              <li>✨ New collections and styles</li>
              <li>🎁 Exclusive offers and discounts</li>
              <li>👁️ Eye care tips and advice</li>
              <li>🌟 Behind-the-scenes content</li>
            </ul>
          </div>
          
          <div style="text-align: center; margin: 30px 0;">
            <a href="${process.env.SITE_URL || 'https://eyeric.com'}" 
               style="background-color: #3b82f6; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; font-weight: bold;">
              Visit Our Store
            </a>
          </div>
          
          <div style="background-color: #fef3c7; padding: 15px; border-radius: 8px; border-left: 4px solid #f59e0b;">
            <p style="margin: 0; color: #92400e; font-size: 14px;">
              <strong>Note:</strong> You can unsubscribe at any time by clicking the unsubscribe link in our emails.
            </p>
          </div>
        </div>
      `,
    };

    // Send confirmation email to user
    await transporter.sendMail(userMailOptions);

    return NextResponse.json(
      { 
        success: true, 
        message: 'Newsletter subscription successful! Check your email for confirmation.' 
      },
      { status: 200 }
    );

  } catch (error) {
    console.error('Newsletter subscription error:', error);
    
    // Log more specific error details
    if (error instanceof Error) {
      console.error('Error message:', error.message);
      console.error('Error stack:', error.stack);
    }
    
    return NextResponse.json(
      { 
        error: 'Failed to process newsletter subscription. Please try again later.',
        details: process.env.NODE_ENV === 'development' ? error instanceof Error ? error.message : 'Unknown error' : undefined
      },
      { status: 500 }
    );
  }
} 